@startuml
'https://plantuml.com/class-diagram
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml

package Agregador <<Folder>> {
    class Administrador {
        nombre: String
    }
    class Contribuyente {
      nombre: String
      apellido: String
      edad: String
    }
    interface FiltroDeHecho {
        boolean filtrar(Hecho hecho)
    }

    class TituloFiltroDeHecho implements FiltroDeHecho {

    }

    class CategoriaFiltroDeHecho implements FiltroDeHecho {

    }

    class FechaDelHechoFiltroDeHecho implements FiltroDeHecho {

    }

    class TipoContenidoMulitmediaFiltroDeHecho implements FiltroDeHecho {

    }
    class Coleccion {
        titulo: String
        descripcion: String
        hechos: Collection<Hecho>
        fuente: FuenteEstatica
        criteriosDePertenencia: FiltrosParaHecho

        void agregarFiltro(FiltroDeHecho filtro)
        void colectarHechos()
        void agregarHecho(Hecho hecho)
    }

    class FiltrosParaHecho {
      filtros: List<FiltroDeHecho>
      boolean aplicarFiltros(Hecho hecho)
      void agregarFiltro(FiltroDeHecho filtro)
    }

    class Hecho {
        titulo: String
        descripcion: String
        categoria: Categoria
        contenidoMultimedia: ContenidoMultimedia
        ubicacion: Ubicacion
        fechaDelHecho: LocalDateTime
        fechaDeCarga: LocalDateTime
        hechoOrigen: HechoOrigen
        etiquetas: Collection<Etiqueta>
        eliminado: boolean

        boolean estaEliminado() {
        void eliminar() {
        void etiquetar(String etiqueta)
    }

    class Etiqueta {
      nombre: String
    }

    class Categoria {
      nombre: String
    }

    class SolicitudDeEliminacionDeHecho {
      solicitudDeEliminacionDeHechoEstado: SolicitudDeEliminacionDeHechoEstado
      fechaCreacion: LocalDateTime
      hecho: Hecho
      motivo: String
      reportador: Contribuyente
      aprobador: Administrador
      fechaResolucion: LocalDateTime

      void rechazar()
      void aprobar()
    }

    enum SolicitudDeEliminacionDeHechoEstado {
      ACEPTADA, RECHAZADA, PENDIENTE
    }

    class Ubicacion {
        latitud: String
        longitud: String
    }

    class ContenidoMulitmedia {
        tipoContenidoMultimedia: TipoContenidoMultimedia
        uri: String
    }

    enum TipoContenidoMulitmedia {
        FOTO
        VIDEO
        AUDIO
    }

    enum HechoOrigen {
        CONTRIBUYENTE
        MANUAL
        EXTERNO
    }

}

package Fuente_Estatica <<Folder>> {
    interface LectorDeArchivo {
      List<List<String>> getRegistros(URI uri)
    }

    class LectorArchivoCSV implements LectorDeArchivo {
      List<List<String>> getRegistros(URI uri)
    }

    interface LocalizadorDeArchivo {
      URI getURI()
    }

    class LocalizadorDeArchivoDelClassPathLocal implements LocalizadorDeArchivo {
      nombreArchivo: String
      tipoArchivo: TipoArchivo

      URI getURI()
    }

    enum TipoArchivo {
      CSV, JSON, TXT
    }

    class FuenteEstatica {
      lectorDeArchivoDeHechos: LectorDeArchivo
      localizadorDeArchivo: LocalizadorDeArchivo
      Collection<Hecho>: traerHechos()
    }
}

package Fuente_Proxy <<Folder>> {
}

package Fuente_Dinamica <<Folder>> {
}


ContenidoMulitmedia --> TipoContenidoMulitmedia

LocalizadorDeArchivoDelClassPathLocal --> TipoArchivo
FuenteEstatica --> LectorDeArchivo
FuenteEstatica --> LocalizadorDeArchivo

FiltrosParaHecho o-- FiltroDeHecho
Coleccion --> FiltrosParaHecho
Coleccion o-- Hecho
Coleccion --> FuenteEstatica

Hecho --> ContenidoMulitmedia
Hecho --> Contribuyente
Hecho --> HechoOrigen
Hecho --> Categoria
Hecho --> Ubicacion
Hecho *-- Etiqueta

SolicitudDeEliminacionDeHecho --> SolicitudDeEliminacionDeHechoEstado
SolicitudDeEliminacionDeHecho --> Contribuyente
SolicitudDeEliminacionDeHecho --> Administrador


@enduml